[2020-09-30 21:14:44,519][werkzeug][INFO] -  * Running on http://127.0.0.1:8081/ (Press CTRL+C to quit)
[2020-09-30 21:14:53,664][werkzeug][INFO] - 127.0.0.1 - - [30/Sep/2020 21:14:53] "[37mGET /set_filter/none/all/none/no/none/none/all HTTP/1.1[0m" 200 -
[2020-09-30 21:14:53,690][werkzeug][INFO] - 127.0.0.1 - - [30/Sep/2020 21:14:53] "[37mGET /get_label_value_on_image/none/0408_17_04_07___i1206_IN_______SM_______CR_TP1_ID29_CAM0_TP1_THR750_CN1586365449615953000_TCN-29_MN.png HTTP/1.1[0m" 200 -
[2020-09-30 21:14:55,041][werkzeug][INFO] - 127.0.0.1 - - [30/Sep/2020 21:14:55] "[37mGET /set_filter/none/all/person/no/none/none/all HTTP/1.1[0m" 200 -
[2020-09-30 21:14:55,160][w3classifier.app][ERROR] - Exception on /get_label_value_on_image/person/0408_17_04_07___i1206_IN_______SM_______CR_TP1_ID29_CAM0_TP1_THR750_CN1586365449615953000_TCN-29_MN.png [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/imt/work/pyqt5-images-classifier/w3classifier/app/views.py", line 59, in get_label_value_on_image
    return jsonify(dbs.get_label_value_on_image(label, im))
  File "/usr/local/lib/python3.6/dist-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/usr/local/lib/python3.6/dist-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/simplejson/__init__.py", line 412, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.6/dist-packages/simplejson/encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/dist-packages/simplejson/encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/dist-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.6/dist-packages/simplejson/encoder.py", line 273, in default
    o.__class__.__name__)
TypeError: Object of type ndarray is not JSON serializable
[2020-09-30 21:14:55,173][werkzeug][INFO] - 127.0.0.1 - - [30/Sep/2020 21:14:55] "[35m[1mGET /get_label_value_on_image/person/0408_17_04_07___i1206_IN_______SM_______CR_TP1_ID29_CAM0_TP1_THR750_CN1586365449615953000_TCN-29_MN.png HTTP/1.1[0m" 500 -
